# Generated by Django 2.0.2 on 2018-03-01 10:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_sn', models.CharField(default='', max_length=50, verbose_name='note唯一货号')),
                ('click_num', models.IntegerField(default=0, verbose_name='note点击数')),
                ('like_num', models.IntegerField(default=0, verbose_name='顶数')),
                ('dislike_num', models.IntegerField(default=0, verbose_name='踩数')),
                ('title', models.TextField(max_length=120, verbose_name='note title')),
                ('content', models.TextField(max_length=20000, verbose_name='note title')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'Tips',
                'verbose_name_plural': 'Tips',
            },
        ),
        migrations.CreateModel(
            name='TipsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('icon', models.CharField(blank=True, help_text='图标', max_length=50, null=True, verbose_name='图标')),
                ('desc', models.TextField(blank=True, help_text='类别描述', null=True, verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, 'tab'), (2, 'go')], help_text='类目级别', verbose_name='类目级别')),
                ('is_hot', models.BooleanField(default=False, help_text='是否最热', verbose_name='是否最热')),
                ('avatar', models.CharField(blank=True, default='/static/img/default-avatar.png', max_length=50, null=True, verbose_name='头像')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('parent_category', models.ForeignKey(blank=True, help_text='父目录', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='tips.TipsCategory', verbose_name='父类目级别')),
            ],
            options={
                'verbose_name': 'Tips类别',
                'verbose_name_plural': 'Tips类别',
            },
        ),
    ]
