# Generated by Django 2.0.2 on 2018-03-01 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_auto_20180301_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tips作者'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tips.TipsCategory', verbose_name='Tips类目'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='Tips点击数'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='content',
            field=models.TextField(max_length=20000, verbose_name='Tips title'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='note_sn',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Tips唯一货号'),
        ),
        migrations.AlterField(
            model_name='tips',
            name='title',
            field=models.TextField(max_length=120, verbose_name='Tips title'),
        ),
    ]
