# Generated by Django 2.0.2 on 2018-03-01 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0003_auto_20180301_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='note_sn',
            new_name='tips_sn',
        ),
    ]
