# Generated by Django 2.0.2 on 2018-03-03 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0017_auto_20180303_1432'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicvote',
            name='favorite',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'False'), (1, 'True')], default=-1, verbose_name='是否收藏此贴'),
        ),
        migrations.AlterField(
            model_name='topicvote',
            name='thanks',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'False'), (1, 'True')], default=-1, verbose_name='是否感谢此贴'),
        ),
        migrations.AlterField(
            model_name='topicvote',
            name='vote',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'False'), (1, 'True')], default=-1, verbose_name='是否喜欢此贴'),
        ),
        migrations.AlterUniqueTogether(
            name='topicvote',
            unique_together={('user', 'topic')},
        ),
    ]
