# Generated by Django 2.0.2 on 2018-03-03 15:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0017_auto_20180303_1432'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_auto_20180303_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.IntegerField(choices=[(-1, 'None'), (0, 'False'), (1, 'True')], default=-1, verbose_name='是否收藏此节点')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.TopicCategory', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户和分类关联表',
                'verbose_name_plural': '用户和分类关联表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='favoritenode',
            unique_together={('user', 'node')},
        ),
    ]
