# Generated by Django 2.0.2 on 2018-03-09 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTopDu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_du', models.IntegerField(default=0, verbose_name='活跃值')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户活跃值',
                'verbose_name_plural': '用户活跃值',
            },
        ),
        migrations.AlterUniqueTogether(
            name='usertopdu',
            unique_together={('user', 'add_time')},
        ),
    ]
