# Generated by Django 2.0.2 on 2018-03-13 13:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0005_auto_20180309_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_type', models.CharField(max_length=30, verbose_name='类型')),
                ('balance', models.IntegerField(verbose_name='数量')),
                ('marks', models.CharField(max_length=30, verbose_name='备注')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户账单',
                'verbose_name_plural': '用户账单',
            },
        ),
    ]
