# Generated by Django 2.0.2 on 2018-03-13 14:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0006_balancedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(False, '未签到'), (True, '已经签到')], verbose_name='是否签到')),
                ('date', models.CharField(max_length=30, verbose_name='签到日期')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.RenameModel(
            old_name='BalanceDetails',
            new_name='BalanceInfo',
        ),
    ]
