# Generated by Django 2.0.2 on 2018-03-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_signedinfo_signed_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedinfo',
            name='date',
            field=models.CharField(max_length=30, unique=True, verbose_name='签到日期'),
        ),
    ]
