# Generated by Django 2.0.2 on 2018-03-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_auto_20180313_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceinfo',
            name='last_balance',
            field=models.IntegerField(default=500, verbose_name='目前余额'),
        ),
    ]
