# Generated by Django 2.0.2 on 2018-03-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20180313_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceinfo',
            name='marks',
            field=models.CharField(max_length=200, verbose_name='备注'),
        ),
    ]
