# Generated by Django 2.0.2 on 2018-03-05 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='category',
            new_name='folder',
        ),
    ]
