# Generated by Django 2.0.2 on 2018-03-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20180301_1324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topiccategory',
            unique_together=set(),
        ),
    ]
