# Generated by Django 2.0.2 on 2018-03-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0008_topicvote_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicvote',
            name='dislike',
            field=models.BooleanField(verbose_name='踩'),
        ),
        migrations.AlterField(
            model_name='topicvote',
            name='like',
            field=models.BooleanField(verbose_name='顶'),
        ),
    ]
