# Generated by Django 2.0.2 on 2018-03-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0009_auto_20180302_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicvote',
            name='dislike',
        ),
        migrations.AlterField(
            model_name='topicvote',
            name='like',
            field=models.BooleanField(verbose_name='是否喜欢此贴'),
        ),
    ]
