# Generated by Django 2.0.2 on 2018-03-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0011_auto_20180303_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicvote',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='是否收藏此贴'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicvote',
            name='thanks',
            field=models.BooleanField(default=False, verbose_name='是否感谢此贴'),
            preserve_default=False,
        ),
    ]
