# Generated by Django 2.0.2 on 2018-03-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0013_auto_20180303_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicvote',
            name='favorite',
            field=models.IntegerField(blank=True, choices=[(-1, 'None'), (0, 'False'), (1, 'True')], null=True, verbose_name='是否收藏此贴'),
        ),
        migrations.AlterField(
            model_name='topicvote',
            name='like',
            field=models.IntegerField(blank=True, choices=[(-1, 'None'), (0, 'False'), (1, 'True')], null=True, verbose_name='是否喜欢此贴'),
        ),
        migrations.AlterField(
            model_name='topicvote',
            name='thanks',
            field=models.IntegerField(blank=True, choices=[(-1, 'None'), (0, 'False'), (1, 'True')], null=True, verbose_name='是否感谢此贴'),
        ),
    ]
