# Generated by Django 2.0.2 on 2018-03-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0015_auto_20180303_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicvote',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='topicvote',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='topiccategory',
            options={'verbose_name': 'Topic类别', 'verbose_name_plural': 'Topic类别'},
        ),
        migrations.RemoveField(
            model_name='topiccategory',
            name='icon',
        ),
        migrations.AddField(
            model_name='topic',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='background_img',
            field=models.CharField(blank=True, default='/static/img/default-avatar.png', max_length=50, null=True, verbose_name='背景图片'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='header_color',
            field=models.CharField(blank=True, help_text='头部颜色', max_length=30, null=True, verbose_name='头部颜色'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='theme_color',
            field=models.CharField(blank=True, default='#001D25', help_text='主题颜色', max_length=30, null=True, verbose_name='主题颜色'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='html_content',
            field=models.TextField(default=models.TextField(max_length=20000, verbose_name='Topic content'), max_length=20000, verbose_name='Topic html content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_sn',
            field=models.CharField(max_length=50, unique=True, verbose_name='Topic唯一sn'),
        ),
        migrations.DeleteModel(
            name='TopicVote',
        ),
    ]
