# Generated by Django 2.0.2 on 2018-03-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0016_auto_20180303_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Topic content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='html_content',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Topic html content'),
        ),
    ]
