# Generated by Django 2.0.2 on 2018-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0018_auto_20180303_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='header_color',
            field=models.CharField(blank=True, default='black', help_text='头部颜色', max_length=30, null=True, verbose_name='头部颜色'),
        ),
    ]
