# Generated by Django 2.0.2 on 2018-03-03 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0019_auto_20180303_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='header_color',
            field=models.CharField(default='#001D25', help_text='头部颜色', max_length=30, verbose_name='头部颜色'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='theme_color',
            field=models.CharField(default='#001D25', help_text='主题颜色', max_length=30, verbose_name='主题颜色'),
        ),
    ]
