# Generated by Django 2.0.2 on 2018-03-03 16:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topic', '0020_auto_20180303_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_sn', models.CharField(max_length=50, unique=True, verbose_name='Link唯一sn')),
                ('click_num', models.IntegerField(default=0, verbose_name='Topic点击数')),
                ('title', models.TextField(max_length=120, verbose_name='Topic title')),
                ('content', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Topic content')),
                ('html_content', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Topic html content')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Link作者')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.TopicCategory', verbose_name='Node分类')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topic',
            },
        ),
    ]
