# Generated by Django 2.0.2 on 2018-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0022_auto_20180303_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='category_type',
            field=models.IntegerField(choices=[(1, 'tab'), (2, 'go')], help_text='node 类型', verbose_name='node 类型'),
        ),
    ]
