# Generated by Django 2.0.2 on 2018-03-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0024_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments', 'verbose_name_plural': 'Comments'},
        ),
    ]
