# Generated by Django 2.0.2 on 2018-03-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0025_auto_20180308_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='comment_num',
            field=models.IntegerField(default=0, verbose_name='Topic 评论数量'),
        ),
    ]
