# Generated by Django 2.0.2 on 2018-03-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0031_auto_20180309_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='html_content',
        ),
        migrations.AddField(
            model_name='topic',
            name='markdown_content',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Topic 内容'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, max_length=20000, null=True, verbose_name='Topic 内容'),
        ),
    ]
