# Generated by Django 2.0.2 on 2018-03-15 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0032_auto_20180315_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='content',
        ),
    ]
