# Generated by Django 2.0.2 on 2018-03-15 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0033_remove_topic_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comments 评论表', 'verbose_name_plural': 'Comments 评论表'},
        ),
        migrations.AlterModelOptions(
            name='nodelink',
            options={'verbose_name': 'NodeLink主表', 'verbose_name_plural': 'NodeLink主表'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Topic主表', 'verbose_name_plural': 'Topic主表'},
        ),
    ]
