# Generated by Django 2.0.2 on 2018-03-15 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0034_auto_20180315_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_comment_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Topic 最后评论时间'),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_comment_user',
            field=models.CharField(default='', max_length=50, verbose_name='Topic 最后评论人名'),
        ),
    ]
