# Generated by Django 2.0.2 on 2018-03-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0035_auto_20180315_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_comment_user',
            field=models.CharField(default='admin', max_length=50, verbose_name='Topic 最后评论人名'),
        ),
    ]
