# Generated by Django 2.0.2 on 2018-03-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0036_auto_20180315_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_comment_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='Topic 最后评论时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_comment_user',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Topic 最后评论人名'),
        ),
    ]
