# Generated by Django 2.0.2 on 2018-03-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0037_auto_20180315_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='last_comment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Topic 最后评论时间'),
        ),
    ]
