# Generated by Django 2.0.2 on 2018-03-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0038_auto_20180315_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccategory',
            name='count_num',
            field=models.IntegerField(default=0, verbose_name='统计此节点下一共有多少个Topic'),
        ),
    ]
