# Generated by Django 2.0.2 on 2018-03-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0039_topiccategory_count_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topiccategory',
            old_name='count_num',
            new_name='count_topic',
        ),
    ]
