# Generated by Django 2.0.2 on 2018-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.IntegerField(choices=[('1', '在线'), ('0', '离线')], default=0, verbose_name='在线状态'),
        ),
    ]
