# Generated by Django 2.0.2 on 2018-03-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20180304_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ONLINE', '在线'), ('OFFLINE', '离线')], default='OFFLINE', max_length=10, verbose_name='在线状态'),
        ),
    ]
