# Generated by Django 2.0.2 on 2018-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20180304_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'verbose_name': 'Following 关系表', 'verbose_name_plural': 'Following 关系表'},
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='status',
            field=models.BooleanField(default=False, verbose_name='关注状态， True 正在关注， False 拉黑名单了'),
            preserve_default=False,
        ),
    ]
