# Generated by Django 2.0.2 on 2018-03-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20180304_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollowing',
            name='status',
            field=models.BooleanField(default=True, verbose_name='关注状态， True 正在关注， False 拉黑名单了'),
        ),
    ]
