# Generated by Django 2.0.2 on 2018-03-04 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20180304_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'verbose_name': '用户的Following 和 Block 关系表', 'verbose_name_plural': '用户的Following 和 Block 关系表'},
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='status',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='is_block',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'False'), (1, 'True')], default=-1, verbose_name='是否Block'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='is_following',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'False'), (1, 'True')], default=-1, verbose_name='是否Following'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
