# Generated by Django 2.0.2 on 2018-03-08 12:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20180304_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(blank=True, max_length=50, null=True, verbose_name='个人网站')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='所在公司')),
                ('company_title', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作职位')),
                ('bio', models.CharField(blank=True, max_length=300, null=True, verbose_name='个人简介')),
                ('balance', models.IntegerField(default=500, verbose_name='财富值，默认500')),
                ('show_balance', models.IntegerField(choices=[(0, '不展示'), (1, '展示')], default=0, verbose_name='是否显示余额')),
                ('list_rich', models.IntegerField(choices=[(0, '不展示'), (1, '展示')], default=0, verbose_name='是否参与财富榜')),
                ('my_home', models.CharField(blank=True, max_length=30, null=True, verbose_name='登录后首页跳转')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterModelOptions(
            name='verifycode',
            options={'verbose_name': '邮箱和手机验证码', 'verbose_name_plural': '邮箱和手机验证码'},
        ),
        migrations.RenameField(
            model_name='verifycode',
            old_name='email',
            new_name='to',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verify',
            field=models.IntegerField(choices=[(0, '未验证'), (1, '已验证')], default=0, verbose_name='Email是否已经验证'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_verify',
            field=models.IntegerField(choices=[(0, '未验证'), (1, '已验证')], default=0, verbose_name='Mobile是否已经验证'),
        ),
        migrations.AddField(
            model_name='verifycode',
            name='code_type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Mobile')], default=0, verbose_name='验证码类型'),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
