# Generated by Django 2.0.2 on 2018-03-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20180308_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='list_rich',
            field=models.IntegerField(choices=[(0, '不展示'), (1, '展示')], default=1, verbose_name='是否参与财富榜'),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='show_balance',
            field=models.IntegerField(choices=[(0, '不展示'), (1, '展示')], default=1, verbose_name='是否显示余额'),
        ),
    ]
