# Generated by Django 2.0.2 on 2018-03-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20180308_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='to',
            field=models.CharField(max_length=30, verbose_name='发送给谁'),
        ),
    ]
