# Generated by Django 2.0.2 on 2018-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20180312_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='用户登录时会写入当前session_key'),
        ),
    ]
