# Generated by Django 2.0.2 on 2018-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20180314_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='task_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='任务的返回id'),
        ),
    ]
