# Generated by Django 2.0.2 on 2018-03-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_verifycode_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifycode',
            name='task_id',
            field=models.CharField(blank=True, max_length=37, null=True, verbose_name='任务的返回id'),
        ),
    ]
